local o = vim.opt

o.number = true
o.relativenumber = false
o.ignorecase = true
o.smartcase = true
o.wrap = false
o.cursorline = true
o.splitright = true
o.splitbelow = true
o.termguicolors = true
o.signcolumn = 'yes'
o.updatetime = 200
o.timeout = true
o.timeoutlen = 500
o.clipboard = 'unnamedplus'
o.expandtab = true
o.shiftwidth = 4
o.tabstop = 4
o.softtabstop = 4
o.smartindent = true
o.equalalways = false
