return {
  { import = 'plugins.colours' },
  { import = 'plugins.core' },
  { import = 'plugins.telescope' },
  { import = 'plugins.oil' },
  { import = 'plugins.treesitter' },
  { import = 'plugins.lsp' },
  { import = 'plugins.cmp' },
  { import = 'plugins.gitsigns' },
  { import = 'plugins.lualine' },
  { import = 'plugins.lazygit' },
  { import = 'plugins.sleuth' },
  { import = 'plugins.editing' },
  { import = 'plugins.todo' },
  { import = 'plugins.aerial' },
}
