return {
  { import = 'plugins.colours' },
  { import = 'plugins.core' },
  { import = 'plugins.telescope' },
  { import = 'plugins.nvimtree' },
  { import = 'plugins.treesitter' },
  { import = 'plugins.lsp' },
  { import = 'plugins.cmp' },
  { import = 'plugins.gitsigns' },
  { import = 'plugins.lualine' },
  { import = 'plugins.lazygit' },
  { import = 'plugins.sleuth' },
  { import = 'plugins.editing' },
  { import = 'plugins.todo' },
  { import = 'plugins.aerial' },
  { import = 'plugins.avante' },
  { import = 'plugins.bufferline' },
  { import = 'plugins.conform' },
  { import = 'plugins.toggleterm' },
  { import = 'plugins.whichkey' },
  { import = 'plugins.bufremove' },
  { import = 'plugins.python.uv' },
}
